//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jp.osakana4242.itunes_furikake.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jp.osakana4242.itunes_furikake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ImgOsakana {
            get {
                object obj = ResourceManager.GetObject("ImgOsakana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ${app.displayName}
        ///バージョン: ${app.version}
        ///
        ///作：三途の川おさかな
        ///Web： https://osakana4242.sakura.ne.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrAppInfo {
            get {
                return ResourceManager.GetString("StrAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iTunesふりかけ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrAppName {
            get {
                return ResourceManager.GetString("StrAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}件の中に削除対象のトラックはみつかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteCheckLog1 {
            get {
                return ResourceManager.GetString("StrDeleteCheckLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteCheckProgress1 {
            get {
                return ResourceManager.GetString("StrDeleteCheckProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実体の無いトラックの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteConfirmForm1 {
            get {
                return ResourceManager.GetString("StrDeleteConfirmForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下記 {0}件 のトラックをライブラリから削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteConfirmForm2 {
            get {
                return ResourceManager.GetString("StrDeleteConfirmForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: [{1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteConfirmForm3 {
            get {
                return ResourceManager.GetString("StrDeleteConfirmForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: [{1}] - 削除失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteNG {
            get {
                return ResourceManager.GetString("StrDeleteNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: [{1}] - 削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteOK {
            get {
                return ResourceManager.GetString("StrDeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteProgress1 {
            get {
                return ResourceManager.GetString("StrDeleteProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除前にトラックを確認する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDeleteProgressCheckbox {
            get {
                return ResourceManager.GetString("StrDeleteProgressCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多重起動は出来ません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrAppDuplicate {
            get {
                return ResourceManager.GetString("StrErrAppDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが見つかりません。
        ///ファイル: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrFile {
            get {
                return ResourceManager.GetString("StrErrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrFormTitle {
            get {
                return ResourceManager.GetString("StrErrFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーが発生しました。
        ///
        ///エラーの詳細: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrFormUnknown {
            get {
                return ResourceManager.GetString("StrErrFormUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Microsoft IME&apos;をインストールしてください。
        ///&apos;{0}&apos;のCLSIDが取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrMSIME1 {
            get {
                return ResourceManager.GetString("StrErrMSIME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos;のインスタンスが作成できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrMSIME2 {
            get {
                return ResourceManager.GetString("StrErrMSIME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iTunesでトラックを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrTrack1 {
            get {
                return ResourceManager.GetString("StrErrTrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一部のトラックの更新に失敗しています。詳細はログをご覧ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrTrack2 {
            get {
                return ResourceManager.GetString("StrErrTrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrExecuting {
            get {
                return ResourceManager.GetString("StrExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他のコマンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommand {
            get {
                return ResourceManager.GetString("StrMenuCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実体の無いトラックの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandDelete {
            get {
                return ResourceManager.GetString("StrMenuCommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読みを降る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandGroupRuby {
            get {
                return ResourceManager.GetString("StrMenuCommandGroupRuby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ひらがなで読みを降る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandRubyHiragana {
            get {
                return ResourceManager.GetString("StrMenuCommandRubyHiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタカナで読みを降る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandRubyKatakana {
            get {
                return ResourceManager.GetString("StrMenuCommandRubyKatakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読みを上書きする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandRubyOverwrite {
            get {
                return ResourceManager.GetString("StrMenuCommandRubyOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに読みが振られているトラックに対しても、読みを振りなおします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandRubyOverwriteTooltip {
            get {
                return ResourceManager.GetString("StrMenuCommandRubyOverwriteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローマ時で読みを降る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandRubyRome {
            get {
                return ResourceManager.GetString("StrMenuCommandRubyRome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全角英数を半角にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuCommandZenkakuToHankaku {
            get {
                return ResourceManager.GetString("StrMenuCommandZenkakuToHankaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuHelp {
            get {
                return ResourceManager.GetString("StrMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMenuHelpVersion {
            get {
                return ResourceManager.GetString("StrMenuHelpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMessageBoxCancel {
            get {
                return ResourceManager.GetString("StrMessageBoxCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMessageBoxOK {
            get {
                return ResourceManager.GetString("StrMessageBoxOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrRootFormLog {
            get {
                return ResourceManager.GetString("StrRootFormLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択中のトラック数: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrRootFormStatusBar1 {
            get {
                return ResourceManager.GetString("StrRootFormStatusBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理したいトラックを iTunes で選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrRootFormStatusBar2 {
            get {
                return ResourceManager.GetString("StrRootFormStatusBar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iTunesふりかけ - 起動中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrStartupFormTitle {
            get {
                return ResourceManager.GetString("StrStartupFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iTunesふりかけのバージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrVersionFormTitle {
            get {
                return ResourceManager.GetString("StrVersionFormTitle", resourceCulture);
            }
        }
    }
}
