//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jp.osakana4242.itunes_furikake.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jp.osakana4242.itunes_furikake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap osakana {
            get {
                object obj = ResourceManager.GetObject("osakana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ${app.displayName}
        ///バージョン: ${app.version}
        ///
        ///作：三途の川おさかな
        ///Web： http://osakana4242.yokochou.com/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrAppInfo {
            get {
                return ResourceManager.GetString("StrAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iTunesふりかけ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrAppName {
            get {
                return ResourceManager.GetString("StrAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MicrosoftIMEをインストールしてください。
        ///&apos;{0}&apos;のCLSIDが取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrMSIME1 {
            get {
                return ResourceManager.GetString("StrErrMSIME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos;のインスタンスが作成できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrMSIME2 {
            get {
                return ResourceManager.GetString("StrErrMSIME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トラックを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrTrack1 {
            get {
                return ResourceManager.GetString("StrErrTrack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一部のトラックの更新に失敗しています。詳細はログをご覧ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrTrack2 {
            get {
                return ResourceManager.GetString("StrErrTrack2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrErrUnknown {
            get {
                return ResourceManager.GetString("StrErrUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrExecuting {
            get {
                return ResourceManager.GetString("StrExecuting", resourceCulture);
            }
        }
    }
}
